### ISSUE TITLE
How to install Julia and Pluto | Week 1 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rohans0509** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#1]

**Comment by rohans0509** [comment]
0:00 Introduction
0:17 Julia: Download
1:11 Julia: Navigating the site
1:18 Julia: Running the Installer
1:44 Starting Julia
1:52 Julia: REPL
2:10 Pluto: Installation
2:20 Julia: Package Manager
2:43 Adding Pluto
3:06 Importing Pluto
3:12 Pluto: Creating a new notebook server
3:29 Pluto: Opening notebook server
3:53 Pluto: Sample notebooks
4:25 Homework 0
4:34 Opening Homework 0 in a Pluto Notebook
5:13 Pluto: Saving the notebook
6:24 Submitting Homework 0 on Canva

**Comment by fonsp** [comment]
![image](https://media.giphy.com/media/D08aklo5n0hi5PJyZw/giphy.gif)

**Comment by logankilpatrick** [comment]
Timestamps added, thank you @rohans0509!! https://www.youtube.com/watch?v=OOjKEgbt8AI
