### ISSUE TITLE
Course Welcome! MIT Computational Thinking Spring 2021 | Lecture 1 | 6.S083 / 18.S191 / 22.S092

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#10]
Hello 😄, now working on Spring 2021 lectures.

[Course Welcome! MIT Computational Thinking Spring 2021 | Lecture 1 | 6.S083 / 18.S191 / 22.S092](https://www.youtube.com/watch?v=3zTO3LEY-cM&list=PLP8iPy9hna6T56GkMHEdSrjCCheNuEwI0)

0:00 Welcome and logistics of the course
3:54 Running the code along
4:50 Setting up Julia
6:20 Quick introduction to the professors
9:10 Administrative stuff for MIT students
10:40 Computer Science and Computational Science Working Together
15:00 Lecture 1: Images as examples of data all around us
16:38 Data: Images (as an example of data)
21:20 Input and Visualize: loading and viewing an Image (in Julia)
23:24 Capturing an image from your own camera
26:06 Inspecting your data
34:18 Process: Modifying an image
40:20 Model: Creating synthetic images
40:28 Output: Saving an image to a file
40:35 Computer science: Arrays
41:20 Julia: constructing arrays
46:18 Pluto: Interactivity using sliders
47:00 Introduction to Abstraction
54:50 First Taste of Abstraction

**Comment by logankilpatrick** [comment]
Added, thank you again!!
