### ISSUE TITLE
Transforming Images , MIT Computational Thinking Spring 2021 | Lecture 2

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#11]
[Transforming Images , MIT Computational Thinking Spring 2021 | Lecture 2](https://www.youtube.com/watch?v=uZYVjDDZW9A&list=PLP8iPy9hna6T56GkMHEdSrjCCheNuEwI0)

1:25 Announcement: Lectures will be nearly an hour
2:30 Unitful.jl package: adding units to numbers just works in Julia
5:40 Transforming images
6:15 Downsampling/Upsampling
8:55 Linear Combinations (Combining images)
12:20 element-wise multiplication (broadcast)
14:48 Convex Combinations
18:35 Fun with Photoshop
23:50 Image Filtering (convolutions)
27:17 Definition of convolutions and kernels
28:04 Computer Science: Complexity
28:51 Computer Science: Architectures, GPUs or Graphical Processing Units
30:50 Playing with a few kernels
41:17 Gaussian Filter
47:05 Computer Science: Data Structure: Offset Arrays
49:00 Discrete vs Continuous
50:55 Respect my Boundaries

Also, I was wondering if it's possible to switch this lecture's position in the playlist to the 2nd position?

**Comment by logankilpatrick** [comment]
Done and Done. Thank you!
