### ISSUE TITLE
Transformations & AutoDiff | MIT Computational Thinking Spring 2021 | Lecture 3

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#12]
Transformations & AutoDiff | MIT Computational Thinking Spring 2021 | Lecture 3

 0:00 Introduction by MIT's Prof. Alan Edelman
 0:35 Agenda of Lecture
 1:30 Transformations and Automatic Differentiations
 2:30 General Linear Transformation
 2:46 Shear Transformation
 4:48 Non-Linear Transformation(Warp) 
 6:12 Rotation
 6:25 Compose Transformation(Rotate followed by Warp)
 7:28 More Transformations(xy, rθ)
 8:01 Linear and Non-Linear Transformations
 9:15 Linear combinations of Images
 9:45 Functions in Maths and in Julia(Short form, anonymous and long form)
14:52 Automatic Differentiation of Univariates
21:16 Scalar Valued Multivariate Functions
27:10 Automatic Differentiation: Scalar valued and Multivariate Functions
30:20 Minimizing "loss function" in Machine Learning
31:35 Transformations: Vector Valued Multivariate Functions
39:42 Automatic Differentiation of Transformations
14:24 But what is a transformation, really? 
49:50 Significance of Determinants in Scaling
53:03 Resource for Automatic Differentiation in 10 minutes with Julia
https://youtu.be/vAp6nUMrKYg
(YouTube video by MIT's Prof. Alan Edelman)

**Comment by logankilpatrick** [comment]
Thank you very much!
