### ISSUE TITLE
Introduction to your professors | Week 1 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#13]
Introduction to your professors | Week 1 | 18.S191 MIT Fall 2020
0:00 Professor David Sanders, Faculty of Sciences, National University of Mexico & Visiting Professor, MIT
0:11 Dr. James Schloss, PhD(2019) from OIST Graduate University, currently working on MIT's CliMA Project
0:21 Professor Alan Edelman (with Co-Prof. Philip the Corgi)
0:31 Grant Sanderson, creator of YouTube channel 3Blue1Brown
0:34 Back to Prof. David Sanders
0:49 Re-entry of Dr. James Schloss
1:07 Over to Grant Sanderson
1:20 Prof. Alan Edelman's kind words
1:31 Welcoming Message
2:03 Syllabus
2:16 First arc-Images and Matrix Manipulation
2:25 Second arc-Time Stepping and Ray tracing
2:30 Next comes Epidemic Modeling followed by Climate Science
2:40 Motive behind topics
3:12 Introduction to Julia technology
3:32 Why Julia?
4:47 Cohesive blend of Computation, Science and Math
5:07 Final Message

**Comment by logankilpatrick** [comment]
Great, thank you! For things like this, no need for so much fidelity in the timestamps. It can be more general.
