### ISSUE TITLE
Seam Carving: Live Coding Session | Week 2 | MIT 18.S191 Fall 2020 | James Schloss

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#14]
00:00 Introduction
03:40 How does a computer tell what is important in the image?
06:02 1st function-Find the energy "function find_energy()"
18:06 Next function-To generate the seam "function find_seam_at()"
20:55 Last Function-To return the seam of minimum energy "function find_seam()"
23:08 Seam Carving of image "function seam_carving()"-find the energy, find the seam and remove the seam from image
25:26 Why this algorithm?

**Comment by logankilpatrick** [comment]
Thank you!!
