### ISSUE TITLE
Structure | Week3 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#15]
Structure | Week3 | 18.S191 MIT Fall 2020

00:00 Introduction
00:10 Matrices
01:53 Vectors in Machine Learning or Linear Algebra
08:28 Diagonal Matrices
10:08 Sparse Matrices
14:14 Another way of compressing Information-Store the Summary
16:46 Another kind of image compression-Outer Product(Multiplication tables), factorizing the Multiplication tables 
23:54 Singular value decomposition(SVD)
25:18 How to use SVD for Computational Thinking?  
28:22 Extracting the structure of an image using SVD
32:28 Final note

**Comment by logankilpatrick** [comment]
Great! Please include the video link for future timestamps. Thanks again!
