### ISSUE TITLE
Understanding structure in data | Week 3 | MIT 18.S191 Fall 2020 | David Sanders

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#16]
Understanding structure in data | Week 3 | MIT 18.S191 Fall 2020 | David Sanders

00:00 Introduction
00:54 Flags
03:16 Rank of a Matrix
05:37 How do we know the data is close to a structured, rank-1 matrix?
07:00 Plotting data using "Plots.jl" in Julia
10:08 Size of the data cloud
11:13 Centre the dataset/"de-meaning"	
12:36 How wide is this dataset? Use Standard Deviation in Julia
15:18 Corelated data 
16:36 Principal Component Analysis
21:04 Visualizing in Higher Dimension
22:54 Application: A simple recommendation engine

**Comment by logankilpatrick** [comment]
Thank you!
