### ISSUE TITLE
Introspection | Week 4 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#17]
Introspection | Week 4 | 18.S191 MIT Fall 2020
 
00:00 Introduction
03:18 Specialized implementations of functions-"methods"
05:01 Generic Programming in Julia-extending functions and using different architectures
07:00 Looking under the hood at code specialization
07:38 "lowered" code, "typed" code, "LLVM" code, "native" code  
12:15 Conclusion

**Comment by logankilpatrick** [comment]
Thank you!
