### ISSUE TITLE
Transformations 2: Composability and Linearity | MIT Computational Thinking Spring 2021 | Lecture 4

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#19]
Transformations 2: Composability and Linearity | MIT Computational Thinking Spring 2021 | Lecture 4

YouTube Link: https://youtu.be/VDPf3RjoCpY

00:00 Introduction
01:10 Playing with transformations
18:16 Why Image Processing to learn Julia?
20:28 Last lecture leftovers: Perspective maps, Linear perspective interactive
24:31 Julia style(advanced): Defining vector valued functions
35:44 Functions with parameters
35:56 Linear transformations: a collection
38:05 Nonlinear transformations: a collection
38:41 Composition
39:48 Difference between sin and sin(x)
51:32 Definition of Linear Transformations 
54:14 To be discussed in next lecture

**Comment by logankilpatrick** [comment]
Done, thank you!
