### ISSUE TITLE
Arrays: slices and views | Week 2 | 18.S191 MIT Fall 2020 | David P. Sanders

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#2]
Hello, I would like to contribute to [Arrays: slices and views | Week 2 | 18.S191 MIT Fall 2020 | David P. Sanders](https://youtu.be/gTGJ80HayK0)

**Comment by logankilpatrick** [comment]
Awesome! Please post the time stamps here when you are done :)

**Comment by rafaelchp** [comment]
I don't know if it's too specific, I hope it is fine.

0:00 Introduction
0:06 Arrays
0:23 |—> Create a 1-dimensional array 
0:42 |—> Index an array
0:59 |—> Modify an array
1:19 |—> Slicing an array
1:59 Modifying a slice
2:30 |—> Broadcasting
3:08 |—> Assign an array to a slice
3:20 Array slices
4:39 |—> Slices are copies of arrays
5:06 Array views
6:35 |—> Comparing types of slices and views of arrays
7:22 `@view` macro
8:30 Matrices: slices and views
9:17 Reshaping matrices
9:52 |—> `vec` function: matrix to vector
10:14 Julia is column major
11:07 Summary

**Comment by logankilpatrick** [comment]
Awesome! Thank you @rafaelchp!!

**Comment by logankilpatrick** [comment]
Just updated the video
