### ISSUE TITLE
Introduction to DataFrames.jl | Week 4 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#20]
Introduction to DataFrames.jl | Week 4 | 18.S191 MIT Fall 2020
https://youtu.be/Pt8Iz4Udg2E

00:00 How to use the CSV and DataFrames packages in Julia
01:50 What is a DataFrame in Julia?
02:06 Using the data
03:52 Extracting useful information
05:58 Using Array comprehension
07:53 Extract a single row 
09:11 Extract Julia  data into vector
09:40 Using dates

**Comment by logankilpatrick** [comment]
Great!
