### ISSUE TITLE
Probability via computation | Week 4 | MIT 18.S191 Fall 2020 | David Sanders

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#21]
Probability via computation | Week 4 | MIT 18.S191 Fall 2020 | David Sanders
https://youtu.be/Yx055xdSkx0

00:00 How to model epidemic propagation?
01:40 Random Sampling using rand()
04:15 Classic experiment of Rolling a die
06:45 Monte Carlo Simulation to plot the frequencies
09:15 Relative frequency or proportion of rolls of the die
12:19 Random variables
14:00 Uniform random numbers
14:45 Visualization: plotting the pre-generated data
18:07 Sample events with a given probability: Bernoulli trials
19:17 Algorithm
20:28 What is Bernoulli random variable? 
20:55 Probability distribution of random variable
21:04 Flipping many biased coins
22:34 Illustration of Central Limit Theorem

**Comment by logankilpatrick** [comment]
🎊
