### ISSUE TITLE
Computational Thinking Illustrated | Week 5 | MIT 18.S191 Fall 2020 | Alan Edelman

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#22]
Computational Thinking Illustrated | Week 5 | MIT 18.S191 Fall 2020 | Alan Edelman
https://youtu.be/6bBFkBCzwh4

00:00 Introduction
02:35 Birthday probability problem using Julia
08:12 Solution using generalization of binomil coefficients
09:21 Why computation thinking?

**Comment by logankilpatrick** [comment]
🥇
