### ISSUE TITLE
Graphs, trees, and spreading disease | Week 5 | MIT 18.S191 Fall 2020 | James Schloss [EDIT]

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#23]
Graphs, trees, and spreading disease | Week 5 | MIT 18.S191 Fall 2020 | James Schloss [EDIT]
https://youtu.be/Wa8xUJ1JhKQ

00:00 Introduction
03:35 What is a graph?
05:42 Creating trees
06:53 How to traverse the tree?
07:48 Idea of Depth first Search
07:53 Idea of Breadth first Search
09:42 Depth first search recursive scheme
11:32 Different ways in which we can recurse through the tree
11:42 How stacks and queues work?
14:51 Function for Depth first search stack
15:53 Function for Breadth first search queue
16:24 How to extend this to SIR model
17:14 Nicky Case simulation
16:09 Classes in SIR model of infection spreading
19:16 Script
22:14 Plot the tree
23:08 Discussion about LightGraphs in Julia

**Comment by logankilpatrick** [comment]
💯
