### ISSUE TITLE
Macroscopic models of epidemic dynamics | Week 6 | 18.S191 MIT Fall 2020 | David Sanders

### ISSUE THREAD

**Issue by rashktech** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#24]
Macroscopic models of epidemic dynamics | Week 6 | 18.S191 MIT Fall 2020 | David Sanders
https://youtu.be/27OXvw3nkh4

00:00 Introduction
01:35 Simple model of recovery
07:32 Deterministic dynamics for the mean: Intuitive derivation
11:08 Derivation using mean of stochastic process 
15:40 Macroscopic description in Continuous-time 
20:48 Full SIR model
23:13 Discrete-time SIR model
24:09 Standard(continuous-time) SIR model

**Comment by logankilpatrick** [comment]
Woohoo, thank you!
