### ISSUE TITLE
Principal Component Analysis | MIT Computational Thinking | Spring 2021 | Lecture 8

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#25]
[Principal Component Analysis | MIT Computational Thinking | Spring 2021 | Lecture 8](
https://www.youtube.com/watch?v=iuKrM_NzxCk&list=PLP8iPy9hna6T56GkMHEdSrjCCheNuEwI0&index=8)

0:00 Introduction: Understanding data
0:40 Rank of a matrix
3:58 Matrix rank
5:10 Effect of noise
5:45 From images to data
11:15 Measuring data cloud "size" – using statistics
16:50 Measuring a "width" of a data set
20:55 Root-mean-square distance: Standard deviation
25:54 Correlated data
26:55 Rotating the axes
28:15 Rotating the data
35:40 Higher dimensions
37:15 What is the Singular-Value Decomposition (SVD)?
50:15 Rotations in 300 dimensions

**Comment by logankilpatrick** [comment]
Thank you again!
