### ISSUE TITLE
Sampling and random variables | MIT Computational Thinking Spring | Lecture 9

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#26]
[Sampling and random variables | MIT Computational Thinking Spring | Lecture 9](https://www.youtube.com/watch?v=7HrpoFZzITI)

0:00 Julia: Useful tidbits
3:27 Random sampling with rand
9:55 Several random objects
15:30 Uniform sampling
20:50 Tossing a weighted coin
30:45 Bar charts and histograms
39:10 Probability densities
39:10 Rolling multiple dice
40:15 Converging shape
45:20 Normalising the y -axis
46:30 Options for plotting functions
51:00 Normalising the x axis

**Comment by logankilpatrick** [comment]
Done, thank you!
