### ISSUE TITLE
Modeling with stochastic simulation | MIT Computational Thinking Spring 2021 | Lecture 10

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#27]
[Modeling with stochastic simulation | MIT Computational Thinking Spring 2021 | Lecture 10](
https://www.youtube.com/watch?v=d8BohH76C7E&list=PLP8iPy9hna6T56GkMHEdSrjCCheNuEwI0&index=10)

7:16 Introduction
8:10 Julia features
9:00 Individual-based ("microscopic") models
11:55 Modelling time to success (or time to failure)
12:50 Visualizing component failure
21:15 String interpolation
28:30 String interpolation (HTML example in Pluto)
35:24 Math: Bernoulli random variables
42:10 Julia: Make it a type!
49:50 Running the stochastic simulation
56:15 Time evolution of the mean: Intuitive derivation

**Comment by logankilpatrick** [comment]
Done!
