### ISSUE TITLE
Random variables as types | MIT Computational Thinking Spring 2021 | Lecture 11

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#28]
[Random variables as types | MIT Computational Thinking Spring 2021 | Lecture 11](
https://www.youtube.com/watch?v=xKAO38UsXo0&list=PLP8iPy9hna6T56GkMHEdSrjCCheNuEwI0&index=11)

0:00 Introduction
2:33 Concepts for today
3:57 Random variables as types
4:15 Random variables
4:39 Gaussian distributions
8:43 Sum of two Gaussians
12:22 Theoretical random variables vs. sampling
14:09 Why define a type at all?
14:30 Defining abstract types for random variables
16:45 Defining a type for a Gaussian random variable
22:00 Sum of two Gaussian random variables
24:18 Probability distribution of a Gaussian
25:54 Sampling from a Gaussian distribution
26:40 More general distributions
28:55 Adding two random variables
37:45 Generic programming: sum
43:35 χ₁² distribution
48:15 Using symbolics

**Comment by logankilpatrick** [comment]
Thank you for this!
