### ISSUE TITLE
Random walks | MIT Computational Thinking Spring 2021 | Lecture 12

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#29]
[Random walks | MIT Computational Thinking Spring 2021 | Lecture 12](
https://www.youtube.com/watch?v=WLQ1l75jSwU&list=PLP8iPy9hna6T56GkMHEdSrjCCheNuEwI0&index=12)

1:20 Introduction 
2:13 Visualising random walks
8:30 Julia concepts
10:42 Motivation: Dynamics of hard discs
11:55 Why use random walks?
12:35 Simple random walk
14:12 Julia: Benchmarking
20:30 Trajectory of a random walk
36:00 Making it more general: Random walks using types
37:05 Mutable vs immutable structs
42:10 Functions with type parameters
48:00 update function discussion, why immutable objects?

**Comment by logankilpatrick** [comment]
Done, thanks!
