### ISSUE TITLE
Defining new types | Week 3 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#3]
Working on [Defining new types | Week 3 | 18.S191 MIT Fall 2020](https://youtu.be/yU8P_cHPn8Q).

This time without the subtopic arrows :sweat_smile:

**Comment by logankilpatrick** [comment]
Thank you! YouTube doesn't like those for some reason

**Comment by rafaelchp** [comment]
No problem. I learned a lot with these lectures. I'll be contributing with some more 😄 

0:00 Why define new types?
1:29 Defining new types
2:05 struct keyword to construct new types
2:57 Create objects of user defined type
4:00 Extract information from the objects
5:18 Mutable vs immutable
5:48 Composite types are immutable by default
6:01 Creating a mutable type

**Comment by logankilpatrick** [comment]
Awesome, thank you!
