### ISSUE TITLE
Random walks II | MIT Computational Thinking Spring | Lecture 13

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#30]
[Random walks II | MIT Computational Thinking Spring | Lecture 13](https://www.youtube.com/watch?v=pIAFHyLmwbM)

7:20 Introduction
8:45 Julia concepts
10:18 Pascal's triangle
23:00 Convolutions build Pascal's triangle!
26:20 Random walks: Independent and identically-distributed random variables
29:30 Random walks as a cumulative sum
31:38 Cumulative sum
42:29 Evolving probability distributions in time
55:25 Implementing time evolution of probabilities

**Comment by logankilpatrick** [comment]
sweet, thank you!
