### ISSUE TITLE
Discrete & Continuous | MIT Computational Thinking Spring 2021 | Lecture 14

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#31]
[Discrete & Continuous | MIT Computational Thinking Spring 2021 | Lecture 14](https://www.youtube.com/watch?v=H6Dcx3YeTkE)

2:40 Introduction
3:10 Julia concepts
3:44 Pedagogical concepts
4:10 Discrete and Continuous
6:15 Heard in the hallways: I only like discrete math. I only like continuous math.
10:10 Indexing and Function Evaluation
14:46 Area
31:10 Area using inscribed squares
38:25 Discrete Random Walks and Brownian Motion

**Comment by logankilpatrick** [comment]
Same here

**Comment by rafaelchp** [comment]
This one is trimmed to the very begining, now I get what you mean. I'll do it for the other two.

**Comment by rafaelchp** [comment]
00:00 Introduction
00:30 Julia concepts
01:04 Pedagogical concepts
01:30 Discrete and Continuous
03:35 Heard in the hallways: I only like discrete math. I only like continuous math.
07:30 Indexing and Function Evaluation
12:06 Area
28:30 Area using inscribed squares
35:45 Discrete Random Walks and Brownian Motion

**Comment by logankilpatrick** [comment]
thank you!
