### ISSUE TITLE
Linear models and simulations | MIT Computational Thinking Spring 2021 | Lecture 15

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#32]
[Linear models and simulations | MIT Computational Thinking Spring 2021 | Lecture 15](https://www.youtube.com/watch?v=O6NTKsR8TjQ&list=PLP8iPy9hna6T56GkMHEdSrjCCheNuEwI0&index=16)

0:00 Waiting for the class to start
3:35 Introduction
5:05 Fahrenheit and Celsius Data Set
6:20 Julia: Data Frames
6:45 Data Frame by Columns with labels
7:58 Data Frame with a matrix
9:00 Reading/Writing CSV (comma separated values) Files
11:35 Noisy Data: Add some random noise to the celsius readings
15:50 Statistics Software Outputs Mysterious Tables
18:04 Regression a few ways
19:28 The "Coef." column in the table gives the slope and intercept of the best fit line
25:08 Demystifying the word "Model"
28:55 Understanding the relationship °C ~ 1 + °F
30:40 Simulating the real world: running many noisy models
31:33 Julia: underscore as a digits separator
31:50 Simulated intercepts (100000 simulations)
36:40 Simulated slopes (100000 simulations)
38:30 Simulated σ (100000 simulations)
43:50 The Linear Model Table
45:03 The Coef column is just the regression formula for the best line
45:13 The Std. error column
47:40 The t column
49:05 The t-distribution
51:20 The Pr(>|t|) column
54:35 Degrees of Freedom

**Comment by logankilpatrick** [comment]
same here

**Comment by rafaelchp** [comment]
I was watching the video right now and the timestamps are correct 😅. Do you mean I should offset the introduction from 3:35 to 0:00 and that you're going to trim the begining of the video?

**Comment by rafaelchp** [comment]
00:00 Introduction
01:30 Fahrenheit and Celsius Data Set
02:45 Julia: Data Frames
03:10 Data Frame by Columns with labels
04:23 Data Frame with a matrix
05:25 Reading/Writing CSV (comma separated values) Files
08:00 Noisy Data: Add some random noise to the celsius readings
12:15 Statistics Software Outputs Mysterious Tables
14:29 Regression a few ways
15:53 The "Coef." column in the table gives the slope and intercept of the best fit line
21:33 Demystifying the word "Model"
25:20 Understanding the relationship °C ~ 1 + °F
27:05 Simulating the real world: running many noisy models
27:58 Julia: underscore as a digits separator
28:15 Simulated intercepts (100000 simulations)
33:05 Simulated slopes (100000 simulations)
34:55 Simulated σ (100000 simulations)
40:15 The Linear Model Table
41:28 The Coef column is just the regression formula for the best line
41:38 The Std. error column
44:05 The t column
45:30 The t-distribution
47:45 The Pr(>|t|) column
51:00 Degrees of Freedom

**Comment by logankilpatrick** [comment]
This video broke after I edited it. Go figure.
