### ISSUE TITLE
Optimization | MIT Computational Thinking Spring 2021 | Lecture 16

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#33]
[Optimization | MIT Computational Thinking Spring 2021 | Lecture 16](https://www.youtube.com/watch?v=44RA9fclTdA)

0:00 Waiting for the class to start
3:25 Welcome, announcements
4:13 Introduction
6:15 Julia concepts
7:45 Line Fitting Many Ways
8:35 Exploratory Data Analysis
9:30 Least Squares fitting to a straight line
10:15 Direct Formulas
11:38 The Linear Algebraist's Formula
13:38 Optimization Methods
13:49 Optim.jl: A package written entirely in Julia for optimization
18:15 Functions of Functions and Computing Power
19:40 JuMP.jl: A popular modelling language for Optimization Problems
22:20 Gradients
23:23 Hand Computation
26:35 Finite Difference Evaluation
28:18 Automatic Differentiation (AutoDiff)
31:25 Gradient Descent can be difficult for complicated functions
40:24 Stochastic Gradient Descent
47:45 Bells and Whistles for optim.jl

**Comment by logankilpatrick** [comment]
Hey @rafaelchp if there's dead time at the beginning of the video, please note that and I will remove it. I did for this video, can you offset the timestamps now?

**Comment by rafaelchp** [comment]
Hello! I haven't been able to access the video. It says now that it is unavailable on my devices. I'll try tomorrow.

**Comment by rafaelchp** [comment]
00:00 Welcome, announcements
00:48 Introduction
02:50 Julia concepts
04:20 Line Fitting Many Ways
05:10 Exploratory Data Analysis
06:05 Least Squares fitting to a straight line
06:50 Direct Formulas
08:13 The Linear Algebraist's Formula
10:13 Optimization Methods
10:24 Optim.jl: A package written entirely in Julia for optimization
14:50 Functions of Functions and Computing Power
16:15 JuMP.jl: A popular modelling language for Optimization Problems
18:55 Gradients
19:58 Hand Computation
23:10 Finite Difference Evaluation
24:53 Automatic Differentiation (AutoDiff)
28:00 Gradient Descent can be difficult for complicated functions
36:59 Stochastic Gradient Descent
44:20 Bells and Whistles for optim.jl

These now start at the previous 3:25. I'm sorry, I cannot review, I don't know why I'm getting an error saying that the video is not available for my device. In fact, it didn't work in any device I tried. Not sure what's wrong.

**Comment by logankilpatrick** [comment]
This video broke too. Nice!

**Comment by logankilpatrick** [comment]
I think it was because I edited with Safari....
