### ISSUE TITLE
Functions and types: Multiple dispatch | Week 3 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#4]
Working on [Functions and types: Multiple dispatch | Week 3 | 18.S191 MIT Fall 2020](https://youtu.be/DXtbaSP_LFI)

**Comment by rafaelchp** [comment]
0:00 Functions on types
1:30 Generic and specialized versions of functions
3:06 Generic functions and their methods
3:50 Defining methods in Pluto
4:01 Multiple dispatch
4:31 Example of multiple dispatch
5:19 @which macro
6:52 Summary

**Comment by logankilpatrick** [comment]
Looks good, just added them. Thanks again!
