### ISSUE TITLE
Environments for programming with Julia | Week 3 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#5]
Me again 😅 

Working on [Environments for programming with Julia | Week 3 | 18.S191 MIT Fall 2020](https://youtu.be/PgeLMzw_-Ww)

**Comment by rafaelchp** [comment]
0:00 Introduction
0:05 Why is programming difficult?
1:16 Programming environments
1:40 Text editors
2:05 Integrated Development Environments
2:56 Notebooks (Pluto.jl & Jupyter)
3:19 Vim workflow example
3:54 Visual Studio Code workflow example
4:30 Pluto.jl workflow example
4:40 Summary

**Comment by logankilpatrick** [comment]
Just added them! Thank you for all of these.
