### ISSUE TITLE
Functions are Objects | Week 4 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#6]
[Functions are Objects | Week 4 | 18.S191 MIT Fall 2020](https://youtu.be/_O-HBDZMLrM)

0:00 Functions are Objects
0:35 Example: rename a function
1:11 Example: array of functions
2:02 Functions as arguments to another function
2:58 Functional programming: map and filter
3:30 filter function
4:50 filter function with anonymous function
5:16 filter function with do block
5:57 map function
6:47 Importance of different syntax styles

**Comment by logankilpatrick** [comment]
Awesome, done! Thank you as always.

**Comment by logankilpatrick** [comment]
@rafaelchp Let me know if you want to get more involved on this front. There's a lot of cleaning up that needs to be done on the YouTube and I have been looking for someone to take the lead on this. 

I could use help with: 
- Adding video descriptions
- Monitoring comments a little
- Making sure videos have good thumbnails
- Finding folks in the Julia community to make new content
- Adding video timestamps

Please ping me on Slack if this is of interest https://julialang.org/slack/
