### ISSUE TITLE
Convolutions on GPUs | Week 2 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#7]
[Convolutions on GPUs | Week 2 | 18.S191 MIT Fall 2020](https://www.youtube.com/watch?v=aa3JkX_cj_I&list=PLP8iPy9hna6Q2Kr16aWPOKE0dz9OnsnIJ&index=8)

0:00 Introduction
0:39 CPU code vs. GPU code timing
1:27 Code portability
2:31 cu() function
3:11 About GPUs
5:13 Cartesian Indices  
6:26 Gaussian filter
7:20 convolve2D function
8:21 Calling convolve2D 
8:50 Conclusion

**Comment by logankilpatrick** [comment]
Nice! Done
