### ISSUE TITLE
Convolutions in the Real World | Week 2 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#8]
[Convolutions in the Real World | Week 2 | 18.S191 MIT Fall 2020](https://www.youtube.com/watch?v=e6WnzfvnFlY&list=PLP8iPy9hna6Q2Kr16aWPOKE0dz9OnsnIJ&index=9)

0:00 Theory and practice: Mens et Manus
0:27 Convolutions in the real world
0:49 Building yourself vs. using a product
1:24 Convolution example with Phillip the corgi image
4:24 A few words about machine learning

**Comment by logankilpatrick** [comment]
Done!
