### ISSUE TITLE
Introduction to macros | Week 3 | 18.S191 MIT Fall 2020

### ISSUE THREAD

**Issue by rafaelchp** [JuliaCommunity/IntroToCompThinkingVideoTimestamps#9]
[Introduction to macros | Week 3 | 18.S191 MIT Fall 2020](https://www.youtube.com/watch?v=e6LGMeoQhfs&list=PLP8iPy9hna6Q2Kr16aWPOKE0dz9OnsnIJ&index=17)

0:00 What are macros?
1:37 @macroexpand macro
3:06 Expressions in Julia
3:47 Quoting an expression
4:38 Expr type in Julia
5:21 Dump an expression object
6:41 Modify fields of an expression
7:30 Metaprogramming

**Comment by logankilpatrick** [comment]
Done. Thank you!!
